# configs/model/hunyuan_train.yaml
defaults:
  - default
  - task: images_only

model_str: "hunyuan_train"

model_config:
  name: "hunyuan_train"
  hf_model_name: "checkpoints/hunyuanworld-mirror"
  load_pretrained_weights: true

  geometric_input_config: ${model.task}
  use_conditioning: true

  img_size: 518
  patch_size: 14
  embed_dim: 1024
  gs_dim: 256
  enable_cam: true
  enable_pts: true
  enable_depth: true
  enable_norm: true
  enable_gs: false
  patch_embed: "dinov2_vitl14_reg"
  fixed_patch_embed: false
  sampling_strategy: "uniform"
  dpt_gradient_checkpoint: true
  condition_strategy: ["token", "pow3r", "token"]

data_norm_type: "identity"
pretrained: null
torch_hub_force_reload: false
