defaults:
  - default
  - encoder: dinov2_large
  - info_sharing: aat_ifr_24_layers
  - pred_head: dpt_pose_scale
  - task: images_only

# String for model factory
model_str: "mapanything_da3_camera_head"
# Model config
model_config:
  name: "mapanything_da3_camera_head"
  encoder_config: ${model.encoder}
  info_sharing_config: ${model.info_sharing}
  pred_head_config: ${model.pred_head}
  geometric_input_config: ${model.task}
  # 
  camera_mode: "fx_fy"
  principal_point_mode: "image_center"
  camera_log_scale_min: -6.0
  camera_log_scale_max: 6.0
  camera_head_config:
    output_dim: 2
# Image Normalization Type
data_norm_type: ${model.encoder.data_norm_type}
